export const SET_USERS = "USERS/SET_USERS";
export const SET_USER_PROFILE = "USER/SET_USER_PROFILE";
export const SET_CURRENT_PAGE = "USER/SET_CURRENT_PAGE";
export const SET_USERS_COUNT = "USER/SET_USERS_COUNT";
